/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:06e536ea-4c58-4f45-9e60-56f91a85f462",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_AZQ1Oiwew",
    "aws_user_pools_web_client_id": "25ts2if005vdmtasgen3tb6776",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://d73erj2wongcnedvydat3mmdba.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-3yyxv2r2ufcfnl4v4qycjdwrl4",
    "aws_user_files_s3_bucket": "dandemoappf18583deaeae425ca253ba18ca4e7cef141446-dev",
    "aws_user_files_s3_bucket_region": "eu-central-1"
};


export default awsmobile;
